#!/bin/sh
#

local_branch="$(git rev-parse --abbrev-ref HEAD)"
echo "${local_branch}"

valid_branch_regex="^(feature|bugfix|improvement|library|prerelease|release|hotfix)\/[a-z0-9._-]+$"

if [[ ! $local_branch =~ $valid_branch_regex ]]; then
echo "\nThere is something wrong with your branch name"
echo "Branch name should be like:"
echo "             bugfix/wrong_safety_item"
exit 1
fi